name: songrec # you probably want to 'snapcraft register <name>'
adopt-info: share
title: SongRec
summary: Unofficial Shazam client for Linux, written in Rust
description: |
  SongRec is an unofficial Shazam client for Linux, written in Rust. It allows you to easily recognize songs from your speakers, microphone or audio files.
  
  Features:
  - Recognize audio from an arbitrary audio file.
  - Recognize audio from the microphone.
  - Usage from both GUI and command line (for the file recognition part).
  - Provide an history of the recognized songs on the GUI, exportable to CSV.
  - Continuous song detection from the microphone, with the ability to choose your input device.
  - Ability to recognize songs from your speakers rather than your microphone (on compatible PulseAudio setups).
license: GPL-3.0+
base: core24 # the base snap is the execution environment for this snap
version: '0.6.4' # just for humans, typically '1.2+git' or '1.3.2'

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  songrec:
    command-chain:
    - snap/command-chain/alsa-launch
    - snap/command-chain/gpu-2404-wrapper
    - snap/command-chain/desktop-launch
    command: bin/songrec
    desktop: usr/share/applications/re.fossplant.songrec.desktop
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - gsettings
      - alsa
      - x11
      - opengl
      - audio-record
      - audio-playback
    slots: [dbus-svc, mpris]

environment:
  ALWAYS_USE_PULSEAUDIO: '1'

slots:
  dbus-svc: # name that is used with 'snap connect' on slots side
    interface: dbus
    bus: session
    name: re.fossplant.songrec

plugs:
  desktop:
    mount-host-font-cache: false
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gtk-4-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404


parts:
  songrec:
    build-packages:
      - libasound2-dev
      - libgtk-4-dev
      - libsoup-3.0-dev
      - libdbus-1-dev
      - libadwaita-1-dev
      - libpulse-dev
      - librsvg2-dev
      - libffi-dev

    stage-packages:
      - pipewire-pulse
      - pipewire-alsa
      - libasound2
      - libgtk-4-1
      - libsoup-3.0-0
      - libadwaita-1-0
      - libpulse0
      - gir1.2-gtk-4.0
      - gir1.2-rsvg-2.0
      - librsvg2-common
      - librsvg2-bin
      - libdbus-1-3
      - ffmpeg
      - libffi8

    plugin: rust
    source: .

    after: [alsa-mixin]

  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev

    stage-packages:
      - pipewire-pulse
      - pipewire-alsa
      - libasound2
      - libasound2-plugins
      - yad

  share:
    plugin: dump
    source: packaging/rootfs/
    parse-info: [usr/share/metainfo/re.fossplant.songrec.metainfo.xml]
    source-type: local

    override-pull: |
      snapcraftctl pull

      # Point icon to the correct location
      sed -i -e 's|Icon=re.fossplant.songrec|Icon=/usr/share/icons/hicolor/scalable/apps/re.fossplant.songrec.svg|g' usr/share/applications/re.fossplant.songrec.desktop

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
